import Head from 'next/head';
import HomeContainer from './components/HomeContainer';

export default function Home() {
  return (

    <div className="root">

      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/store_icon-icons.com_54371.ico" />
      </Head>


      <HomeContainer/>

      
    </div>
  )
}
